use lsj;

CREATE TABLE `member` (
  `USER_NUM` int(4) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(50) NOT NULL,
  `PHONE_NUM` varchar(13) NOT NULL,
  `BIRTHDAY` date NOT NULL,
  `GENDER` char(6) NOT NULL,
  `ADDR` varchar(100) DEFAULT NULL,
  `deleted_at` date DEFAULT NULL,
  PRIMARY KEY (`USER_NUM`)
) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=utf8;

CREATE TABLE `genre` (
  `GENRE_CODE` varchar(13) NOT NULL,
  `RENTAL_FEE` int(5) NOT NULL,
  `LATE_FEE` int(5) NOT NULL,
  `GENRE_NAME` varchar(8) NOT NULL,
  `LEND_TIME` int(1) NOT NULL,
  PRIMARY KEY (`GENRE_CODE`),
  UNIQUE KEY `genre_GENRE_NAME_uq` (`GENRE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `video` (
  `VIDEO_CODE` char(10) NOT NULL,
  `GENRE_CODE` varchar(13) NOT NULL,
  `VIDEO_TITLE` varchar(100) NOT NULL,
  `MOVIE_RATED` int(2) NOT NULL,
  `RELEASE_DATE` date NOT NULL,
  `PRODUCTION` varchar(100) DEFAULT NULL,
  `DIRECTOR` varchar(30) NOT NULL,
  `TOTAL_VIEW` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`VIDEO_CODE`),
  KEY `VIDEO_GENRE_CODE_FK` (`GENRE_CODE`),
  CONSTRAINT `VIDEO_GENRE_CODE_FK` FOREIGN KEY (`GENRE_CODE`) REFERENCES `genre` (`GENRE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `rent` (
  `NUM` int(11) NOT NULL AUTO_INCREMENT,
  `USER_NUM` int(4) NOT NULL,
  `VIDEO_CODE` char(10) NOT NULL,
  `GENRE_CODE` varchar(13) NOT NULL,
  `RENTDATE` date NOT NULL,
  `ISRETURN` char(1) NOT NULL DEFAULT 'N',
  `ADD_LATE_FEE` mediumint(9) DEFAULT NULL,
  `CHECK_LATE` char(1) DEFAULT 'N',
  `RETURN_DUE_DATE` date DEFAULT NULL,
  `RETURN_DATE` date DEFAULT NULL,
  PRIMARY KEY (`NUM`),
  KEY `rent_USER_NUM_FK` (`USER_NUM`),
  KEY `rent_VIDEO_CODE_FK` (`VIDEO_CODE`),
  KEY `rent_GENRE_CODE_FK` (`GENRE_CODE`),
  CONSTRAINT `rent_GENRE_CODE_FK` FOREIGN KEY (`GENRE_CODE`) REFERENCES `genre` (`GENRE_CODE`),
  CONSTRAINT `rent_USER_NUM_FK` FOREIGN KEY (`USER_NUM`) REFERENCES `member` (`USER_NUM`),
  CONSTRAINT `rent_VIDEO_CODE_FK` FOREIGN KEY (`VIDEO_CODE`) REFERENCES `video` (`VIDEO_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=210 DEFAULT CHARSET=utf8 COMMENT='대여기록 테이블';
